
const colors = {
  'white': 'var(--dh-color-white)',
  'black': 'var(--dh-color-black)',
  'primary': 'var(--dh-color-primary)',
  't0': 'var(--dh-color-background)',
  't1': 'var(--dh-color-background-t1)'
};

const spacing = {
  '0': 'var(--dh-space-0)',
  'half': 'var(--dh-space-half)',
  '1': 'var(--dh-space-1)',
  '2': 'var(--dh-space-2)',
  '3': 'var(--dh-space-3)',
  '4': 'var(--dh-space-4)',
  '5': 'var(--dh-space-5)',
  '6': 'var(--dh-space-6)',
  '7': 'var(--dh-space-7)',
  '8': 'var(--dh-space-8)'
};

const screens = {
  'large': 'var(--dh-screen-large)',
  'desktop': 'var(--dh-screen-desktop)',
  'tablet': 'var(--dh-screen-tablet)',
  'mobile': 'var(--dh-screen-mobile)',
  'small': 'var(--dh-screen-small)'
};

const widths = {
  'auto': 'auto',
  'full': '100%',
  ...spacing,
  ...screens
};

const heights = {
  'full': '100vh',
  ...spacing,
  ...screens
};

const border = {
  '0': 'var(--dh-border-0)',
  'DEFAULT': 'var(--dh-border-default)',
  '1': 'var(--dh-border-1)',
  '2': 'var(--dh-border-2)',
  '3': 'var(--dh-border-3)',
  '4': 'var(--dh-border-4)',
  '5': 'var(--dh-border-5)',
  '6': 'var(--dh-border-6)',
  '7': 'var(--dh-border-7)',
  '8': 'var(--dh-border-8)'
};

const fontFamilies = {
  'primary': 'var(--dh-font-family-primary)',
  'secondary': 'var(--dh-font-family-secondary)'
};

const lineHeights = {
  'primary': 'var(--dh-line-height-primary)',
  'secondary': 'var(--dh-line-height-secondary)'
};

module.exports = {
  purge: false,
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: colors,
    // fill: tokens.colors,
    // stroke: tokens.colors,
    // fontFamily: fontFamilies,
    // fontSize: tokens.fontSize,
    // lineHeight: lineHeights,
    width: widths,
    maxWidth: widths,
    height: heights,
    minHeight: heights,
    spacing: spacing,
    borderWidth: border,
    borderRadius: border,
    // boxShadow: {
    //   'none': 'none',
    //   'up': '8px 8px 0px 0px var(--nyco-box-shadow-color)',
    //   'up-2': '16px 16px 0px 0px var(--nyco-box-shadow-color)'
    // },
    screens: screens,
    // margin: spacing
  },
  // plugins: [
  //   logical
  // ],
  variants: {
    // preflight: [],
    // container: [],
    accessibility: ['responsive'],
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    animation: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundClip: [],
    backgroundColor: ['hover', 'focus'],
    backgroundImage: [],
    backgroundOpacity: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: ['hover', 'focus'],
    // borderOpacity: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    boxSizing: [],
    clear: [],
    cursor: [],
    display: ['responsive'],
    divideColor: [],
    divideOpacity: [],
    divideStyle: [],
    divideWidth: [],
    fill: [],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: [],
    fontFamily: [],
    fontSize: ['responsive'],
    fontSmoothing: [],
    fontStyle: [],
    fontVariantNumeric: [],
    fontWeight: [],
    gap: ['responsive'],
    gradientColorStops: [],
    gridAutoColumns: ['responsive'],
    gridAutoFlow: ['responsive'],
    gridAutoRows: ['responsive'],
    gridColumn: ['responsive'],
    gridColumnEnd: ['responsive'],
    gridColumnStart: ['responsive'],
    gridRow: ['responsive'],
    gridRowEnd: ['responsive'],
    gridRowStart: ['responsive'],
    gridTemplateColumns: ['responsive'],
    gridTemplateRows: ['responsive'],
    height: [],
    inset: [],
    justifyContent: ['responsive'],
    justifyItems: [],
    justifySelf: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    logical: ['responsive'],
    margin: ['responsive'],
    maxHeight: [],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    order: ['responsive'],
    outline: [],
    overflow: ['responsive'],
    overscrollBehavior: [],
    padding: ['responsive'],
    placeContent: [],
    placeholderColor: [],
    placeholderOpacity: [],
    placeItems: [],
    placeSelf: [],
    pointerEvents: [],
    position: [],
    resize: [],
    // ringColor: [],
    // ringOffsetColor: [],
    // ringOffsetWidth: [],
    // ringOpacity: [],
    // ringWidth: [],
    rotate: [],
    scale: [],
    skew: [],
    space: [],
    stroke: [],
    strokeWidth: [],
    tableLayout: [],
    textAlign: ['responsive'],
    textColor: ['hover', 'focus'],
    textDecoration: [],
    textOpacity: [],
    textOverflow: [],
    textTransform: [],
    transform: [],
    transformOrigin: [],
    transitionDelay: [],
    transitionDuration: [],
    transitionProperty: [],
    transitionTimingFunction: [],
    translate: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: ['responsive'],
    wordBreak: [],
    zIndex: [],
  },
  corePlugins: [
    // 'preflight',
    // 'container',
    'accessibility',
    'alignContent',
    'alignItems',
    'alignSelf',
    'animation',
    'appearance',
    // 'backgroundAttachment',
    // 'backgroundClip',
    'backgroundColor',
    // 'backgroundImage',
    // 'backgroundOpacity',
    // 'backgroundPosition',
    // 'backgroundRepeat',
    // 'backgroundSize',
    // 'borderCollapse',
    'borderColor',
    // 'borderOpacity',
    'borderRadius',
    'borderStyle',
    'borderWidth',
    'boxShadow',
    'boxSizing',
    'clear',
    'cursor',
    'display',
    // 'divideColor',
    // 'divideOpacity',
    // 'divideStyle',
    // 'divideWidth',
    'fill',
    'flex',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    // 'float',
    'fontFamily',
    'fontSize',
    // 'fontSmoothing',
    'fontStyle',
    // 'fontVariantNumeric',
    'fontWeight',
    'gap',
    // 'gradientColorStops',
    'gridAutoColumns',
    'gridAutoFlow',
    'gridAutoRows',
    'gridColumn',
    'gridColumnEnd',
    'gridColumnStart',
    'gridRow',
    'gridRowEnd',
    'gridRowStart',
    'gridTemplateColumns',
    'gridTemplateRows',
    'height',
    'inset',
    'justifyContent',
    'justifyItems',
    'justifySelf',
    // 'letterSpacing',
    'lineHeight',
    'listStylePosition',
    'listStyleType',
    'margin',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    // 'objectFit',
    // 'objectPosition',
    // 'opacity',
    // 'order',
    // 'outline',
    'overflow',
    'overscrollBehavior',
    'padding',
    // 'placeContent',
    // 'placeholderColor',
    // 'placeholderOpacity',
    // 'placeItems',
    // 'placeSelf',
    'pointerEvents',
    'position',
    'resize',
    // 'ringColor',
    // 'ringOffsetColor',
    // 'ringOffsetWidth',
    // 'ringOpacity',
    // 'ringWidth',
    'space',
    'stroke',
    'strokeWidth',
    'tableLayout',
    'textAlign',
    'textColor',
    'textDecoration',
    // 'textOpacity',
    'textOverflow',
    'textTransform',

    // Transform needs to be the first module before other translate modules
    'transform',
    'transformOrigin',
    'translate',
    'rotate',
    'scale',
    'skew',

    'transitionDelay',
    'transitionDuration',
    'transitionProperty',
    'transitionTimingFunction',
    // 'userSelect',
    'verticalAlign',
    'visibility',
    'whitespace',
    'width',
    'wordBreak',
    'zIndex',
  ]
}
